### ISSUE TITLE
Update tokio

### ISSUE THREAD

**Issue by Nexmean** [telegram-rs/telegram-bot#103]
Hi there :)

`tokio-core` is scheduled for deprecation in favor of `tokio`. May be we should migrate to `tokio`?

I took on this task.
Progress:

- [x] Remove support of `tokio_curl` because of it's dependents on `tokio_core`
- [x] Add support of `tokio` and `hyper = "0.12"`
- [x] Rewrite outdated examples and tests
- [ ] Test library with `tokio`
- [ ] Rewrite outdated docstrings
- [ ] Return support of `tokio_core` via `future` in `Cargo.toml`
- [ ] Test library with `tokio_core`

[Branch with implementation](https://github.com/Nexmean/telegram-bot/tree/feature/tokio_%23103)

**Comment by Nexmean** [comment]
I think if we move to `tokio`, we can't support `tokio-curl`, because `tokio-curl` dependents on `tokio-core`.

**Comment by Nexmean** [comment]
We have some problems. In `telegram_bot_raw` structs often does not implement `Send` trait, because of this we can't start bot on `tokio` thread pool.

**Comment by Nexmean** [comment]
I have done it. Now I need time for testing, edit examples and docs.

**Comment by Nexmean** [comment]
Updated all examples

**Comment by shouya** [comment]
Very nice job Nexmean! I look forward for this change to get merged.

However, I'm concerning if the dev likes it to remove curl-connector. I don't think there's a reason to keep curl-connector since currently hyper is mature enough IMO.

Anyway, if the dev in this repo doesn't want to accept it, or doesn't have time to review your PR, I'd like check it out and include this feature to my [own fork](https://github.com/shouya/telegram-bot-rust).

**Comment by rossnomann** [comment]
> I don't think there's a reason to keep curl-connector since currently hyper is mature enough IMO.
curl-connector allows to specify a proxy. How can I do it with hyper?

**Comment by shouya** [comment]
@rossnomann That makes sense. Does [tafia/hyper-proxy](https://github.com/tafia/hyper-proxy) work for you?

If this crate works we can probably add proxy support for telegram-bot. What else curl-connector features can you think of that hyper doesn't have?

Here's another one, hyper doesn't have built-in multipart support, so it's kind of hard to add features like file uploading. It took me some efforts but I'm finally able to support file sending (in #97). So this shouldn't be a problem either.

**Comment by gugahoa** [comment]
If the author is still interested in continuing the work, or if anyone else wants to implement this enhancement, I'll be happy to review it

**Comment by gugahoa** [comment]
Everything async related has been updated
