### ISSUE TITLE
Downloading a File using the Libary

### ISSUE THREAD

**Issue by Chase22** [telegram-rs/telegram-bot#107]
I'm pretty new to this libary and rust for that matter and as a starter wanted to rewrite a bot i created in java earlier.

For that i'll have to handle and download files, and this is where i am stuck.
I know in order to download a file you have to:
1) Get the message containing the Document
2) Use the Document to make a GetFile request to telegram
3) Get the Filepath from the response
4) Download the file from the telegram servers

I'm stuck at Number 2 

```rust
fn handle_file(doc: &Document, chat_id: &ChatId, api: &Api) {
    if doc.file_size.unwrap() > 20000000 {
        api.spawn(SendMessage::new(chat_id, "The file is to big too download. Please send at maximum 20MB files"));
    } else {
        let mut future: TelegramFuture<telegram_bot::File> = api.send(GetFile::new(doc));
        loop { 
            let result = match future.poll() {
            Ok(async) => {
                match async {
                futures::Async::Ready(result) => {
                    println!("{:?}", result);
                    break;
                },
               futures::Async::NotReady => {println!("Not Ready");}
           }
        },
        Err(e) => {panic!("Polling Error")},
    };
    }
}
```

The Future never get's resolved and always returns "Not Ready" in the console

**Comment by knsd** [comment]
Guess it's outdated. However maybe function works without tokio execution context. And I don't understand why it use manual polling instead of Future::and_then
