### ISSUE TITLE
Update hyper to 0.12?

### ISSUE THREAD

**Issue by upsuper** [telegram-rs/telegram-bot#113]
hyper 0.12 has been released for quite a while. Maybe consider upgrading to that?

**Comment by bemyak** [comment]
@Emulator000 , I think you should fork it! The project really deserves more active live =)

**Comment by Emulator000** [comment]
@bemyak done! ;) you can use my GitHub fork or the forked crate: `telegram-bot-fork`

**Comment by bemyak** [comment]
Thank you! I've been using one of your branches and didn't know there is a published package.

**Comment by gugahoa** [comment]
Fixed by commit da1dc47cdda01b4c974159e0c35735c1d05a2086
