### ISSUE TITLE
Move away from error-chain

### ISSUE THREAD

**Issue by gugahoa** [telegram-rs/telegram-bot#120]
Move away from error-chain as it is now deprecated.
We can go towards using the std error, as it has seen some improvements, or failure as it's the community-chosen way to handle errors

**Comment by robinhundt** [comment]
As a replacement for `error-chain`, [snafu](https://github.com/shepmaster/snafu) could be evaluated. Seems like it cuts down on the boilerplate while being compatible with `std::error::Error`.

If i find the time in the coming weeks i'll have a go at it :blush:

**Comment by Empty2k12** [comment]
There's also https://github.com/dtolnay/thiserror which is quite new but looks promising!

**Comment by knsd** [comment]
I really like the idea of using std error. And maybe it's better to make Error opaque.
