### ISSUE TITLE
I got an error using the example run

### ISSUE THREAD

**Issue by NinjaMoon** [telegram-rs/telegram-bot#123]
I got an error using the example run

 rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.34.2 (6c2484dc3 2019-05-13)

https://github.com/telegram-rs/telegram-bot/blob/master/lib/examples/simple.rs

[dependencies]
telegram-bot = "0.6"
tokio-core = "0.1"
futures = "0.1"

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libcore/result.rs:798
  10: rust_bot::main
             at src/main.rs:14
  11: std::rt::lang_start::{{closure}}
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start

Process finished with exit code 101

**Comment by gugahoa** [comment]
Could you try using telegram-bot master?

**Comment by gugahoa** [comment]
It's because it couldn't find TELEGRAM_BOT_TOKEN environment var set. Just changed the unwrap to expect to give a better feedback on the examples

**Comment by NinjaMoon** [comment]
[dependencies]
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot.git" }
tokio-core = "*"
futures = "*"

**Comment by gugahoa** [comment]
Try setting the env var TELEGRAM_BOT_TOKEN before running the command, for example:
`TELEGRAM_BOT_TOKEN=xxxx cargo run --example simple`

**Comment by NinjaMoon** [comment]
TELEGRAM_BOT_TOKEN=MY TELEGRAM_BOT_TOKEN cargo run main.rs 

    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `/home/ogmck/CLionProjects/rust_bot/target/debug/rust_bot main.rs`
thread 'main' panicked at 'TELEGRAM_BOT_TOKEN not set: NotPresent', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libcore/result.rs:827
  10: rust_bot::main
             at src/main.rs:14
  11: std::rt::lang_start::{{closure}}
             at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start

**Comment by gugahoa** [comment]
You're not running it correctly.
1 - Create a bot here, and get your authorization token: https://core.telegram.org/bots#6-botfather
2 - Change the xxx in `TELEGRAM_BOT_TOKEN=xxxx cargo run --example simple` to the token you retrieve in the previous step, and run as is
