### ISSUE TITLE
Other ways to run update loop

### ISSUE THREAD

**Issue by aDogCalledSpot** [telegram-rs/telegram-bot#124]
Currently, only one way of running the bot is presented in the examples although in the readme it says "via long poll method", so it would be good to see some other methods in the examples.

Specifically, I need to do execute a different function in every iteration of the program, so it would be great if I could have something like:

```rust
loop {
     core.turn(duration);
     do_other_stuff();
}
```

But I'm having trouble adding the futures to core's event loop since the required signature of the future for `core.execute` is different to the one we can use for `core.run`.

**Comment by gugahoa** [comment]
Could you elaborate a little bit more on your constraints?
Is using two threads out of question? If not, you could run the bot in one thread and your code in another one, but it would not be guaranteed that your function will run exactly once per bot iteration

**Comment by aDogCalledSpot** [comment]
I would need access to the bot in the other function as well.

I'm checking for emails in another thread and sending over relevant information to the bot via a channel. The bot will then send the parsed email into a specific chat. I also need to be able to react to other updates so having only the sending of the emails be processed isn't sufficient.

**Comment by xiaods** [comment]
yes, i also need handle similar use case for telegram bot. i don't need update message, i just want to loop another thread and found some new event, i can send message directly. but i can't found any good example for it.

**Comment by xiaods** [comment]
@aDogCalledSpot do you got the thing done?

**Comment by aDogCalledSpot** [comment]
Unfortunately not.

**Comment by knsd** [comment]
I don't quite understand the question.

Library only supports tokio event loop for now.

You can use futures::Stream.select combinator to get updates from both bot and your channel with events.

Feel free to reopen issue.
