### ISSUE TITLE
how i can upload picture to telegram server ?

### ISSUE THREAD

**Issue by robatipoor** [telegram-rs/telegram-bot#127]

**Comment by gugahoa** [comment]
Sorry, I didn't quite understand your question, is it related to telegram-bot or to Rust in general?

**Comment by robatipoor** [comment]
how i can upload picture to telegram server ??? related to telegram bot

**Comment by gugahoa** [comment]
Right now you can send a document via this https://core.telegram.org/bots/api#senddocument, you can see an example of it in action here: https://github.com/telegram-rs/telegram-bot/blob/master/lib/examples/send_document.rs

We don't support file upload right now, but it's an open PR that could receive a review if you want to: https://github.com/telegram-rs/telegram-bot/pull/97
