### ISSUE TITLE
Bot panics on receiving CallbackQuery

### ISSUE THREAD

**Issue by mvlabat** [telegram-rs/telegram-bot#129]
When I press `InlineKeyboardButton` in the message I sent with `InlineQueryResult`, my bot panics with the following error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Raw(Json(Error("missing field `message`", line: 2, column: 262))), State { next_error: None, backtrace: Some(stack backtrace:
>    0: error_chain::make_backtrace::h29dcad393cd2622f (0x55cf07fca4c9)

Full backtrace:
https://gist.github.com/mvlabat/0be7553ef658f9e34fe592cdc48a9643

**Comment by gugahoa** [comment]
Could you publish your code somewhere for further investigation? I wasn't able to pinpoint where the error is coming from with only the backtrace

**Comment by mvlabat** [comment]
@gugahoa, sure!
https://github.com/mvlabat/mirtrs
