### ISSUE TITLE
Docs for master branch are not uploaded

### ISSUE THREAD

**Issue by robinhundt** [telegram-rs/telegram-bot#143]
The docs that can be found under the [docs for master link](https://telegram-rs.github.io/telegram-bot/telegram_bot/) are outdated.  
The `deploy.sh` script, called as `after_success` in the CI pipeline fails with the following error:

```
remote: Permission to telegram-rs/telegram-bot.git denied to LukasKalbertodt.
fatal: unable to access 'https://[secure]@github.com/telegram-rs/telegram-bot.git/': The requested URL returned error: 403
```
(See [latest pipeline output](https://travis-ci.org/telegram-rs/telegram-bot/jobs/593122409)).

Also the way it is set up at the moment, the docs for this crate, as well as all it's dependencies are built and then pushed to the the `gh-pages` branch. This causes the current repo to be over 60M big.  
  

I'm not sure how the GitHub pages feature works, but if the docs for the master branch are to be fixed, I'd advocate for only building the docs for this crate and ignoring dependencies (reduces CI time). The documentation should then not be part of this repo but be hosted externally (Gitlab has artifacts for this, not sure if there is something similar for Github/Travis).

**Comment by gugahoa** [comment]
The current pipeline was created by a maintainer that is not active anymore. Do you have any recommendation on how to setup a better CI? I'm not against scraping what we currently have and making everything anew

**Comment by knsd** [comment]
I've fixed docs for master branch. However 60MB repository is an issue. We can use dedicated repo, like telegram-rs/telegram-bot-docs for master branch docs, what do you think @gugahoa?

**Comment by robinhundt** [comment]
It seems like the usual pattern is to use a a gh-pages branch with no history. Meaning if no docs get committed, the previous commit on the branch is overwritten. Keeping a history of the docs is not really necessary since they can be rebuild anyway from the sources for older versions.
To further reduce the repo size, the docs should build without dependencies.

It also seems weird to push the docs via the account of a former contributor, this should be handled by travis. I haven't worked with travis before but [this link](https://docs.travis-ci.com/user/deployment/pages/) seems to describe how to setup the deployment of the docs (`keep_history` should be set to false).
