### ISSUE TITLE
Trait to get text body for any message kind

### ISSUE THREAD

**Issue by timvisee** [telegram-rs/telegram-bot#144]
A while back I implemented a trait to get the text body for any message kind (along with some other ones), to prevent implementing huge `match` statements throughout the code.

Would it be useful to implement something like this in the core `telegram-bot` crate? If so, I can take this task on me.

Example implementation:
https://github.com/timvisee/risc-bot/blob/10905c5efa9a8067ac202db93f28dc1a6e2c8f6e/src/traits.rs#L3-L60

**Comment by gugahoa** [comment]
Seems like an useful trait to have, you're welcome to contribute it :)
