### ISSUE TITLE
compatibility with `async-std`

### ISSUE THREAD

**Issue by SheldonNico** [telegram-rs/telegram-bot#185]
Use other runtime other than tokio may fail.  I think it's the the same problem in this issue: [https://github.com/tokio-rs/tokio/issues/1466](https://github.com/tokio-rs/tokio/issues/1466). 

```rust
use telegram_bot::*;

use std::io::Write;

async fn main_tele() -> Result<(), Error> {
    let token = env::var("TELEGRAM_BOT_TOKEN").unwrap_or("my token here".to_string());
    let api = Api::new(token);

    // Fetch new updates via long poll method
    let mut stream = api.stream();
    while let Some(update) = stream.next().await {
        // If the received update contains a new message...
        let update = update?;
        if let UpdateKind::Message(message) = update.kind {
            if let MessageKind::Text { ref data, .. } = message.kind {
                // Print received text message to stdout.
                println!("<{}>: {}", &message.from.first_name, data);

                // Answer message with "Hi".
                api.send(message.text_reply(format!(
                    "Hi, {}! You just wrote '{}'",
                    &message.from.first_name, data
                )))
                .await?;
            }
        }
    }
    Ok(())
}

fn main() {
    task::block_on(main_tele());
}
```

result:
![image](https://user-images.githubusercontent.com/11974052/68175816-6b8fd180-ffbd-11e9-878d-aaae130fb944.png)

Search in the source code, the tokio dependency  is quite small. Is it possible to remove `tokio::timer` to increase compatibility with `async_std`? 

![image](https://user-images.githubusercontent.com/11974052/68175967-fe307080-ffbd-11e9-9c74-f5920722146f.png)

**Comment by gugahoa** [comment]
This is a implementation detail from tokio it seems, as it starts the timer when you use their runtime, what we can do is document somewhere how to run telegram-bot with async-std (which can be done following this comment https://github.com/tokio-rs/tokio/issues/1466#issuecomment-522300040)

**Comment by SheldonNico** [comment]
Ok, I will use this way. It's better than import all tokio runtime.
