### ISSUE TITLE
UpdatesStream is not Send => can't be used with spawn()

### ISSUE THREAD

**Issue by netvl** [telegram-rs/telegram-bot#192]
This very simple piece of code fails to compile with a very scary error:
```rust
fn test_bot() {
    tokio::task::spawn(async {
        let api: Api = todo!();
        let updates = api.stream().fuse();
        loop {
            select! {
                upd = updates.select_next_some() => println!("{:?}", upd),
            }
        }
    });
}
```
```
error[E0277]: `(dyn core::future::future::Future<Output = std::result::Result<std::option::Option<std::vec::Vec<telegram_bot_raw::types::update::Update>>, telegram_bot::errors::Error>> + 'static)` cannot be sent between threads safely
   --> src/server/bot.rs:56:5
    |
56  |     tokio::task::spawn(async {
    |     ^^^^^^^^^^^^^^^^^^ `(dyn core::future::future::Future<Output = std::result::Result<std::option::Option<std::vec::Vec<telegram_bot_raw::types::update::Update>>, telegram_bot::errors::Error>> + 'static)` cannot be sent between threads safely
    | 
   ::: /home/netvl/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/task/spawn.rs:123:21
    |
123 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::task::spawn::spawn`
    |
...
```

This error points out the fact that the [`current_request` field](https://github.com/telegram-rs/telegram-bot/blob/16147f62247497457e1af824e4bf732b67b61f1c/lib/src/stream.rs#L27) is not `Send`, because the nested trait object is not `Box<... + Send>`.

This seems to make it impossible to run any kind of update handling procedure in sub-tasks (created by various `spawn` methods), but only in the "main" task (created by the `block_on` kind of methods). This is unfortunately a hard restriction for many complex projects.

**Comment by gugahoa** [comment]
Closed by #200

**Comment by zvirja** [comment]
@gugahoa Could you please trigger a new release so we can consume this change?

**Comment by stickybath** [comment]
Only disadvantage to this is that I'm also using the tracing crate. My application is now being flooded with trace and debug messages from this crate...
