### ISSUE TITLE
No associated function "new" for api

### ISSUE THREAD

**Issue by mrhajbabaei** [telegram-rs/telegram-bot#198]
Hi, I just want to the simple example, but I got this error:
`error[E0599]: no function or associated item named `new` found for type `telegram_bot::api::Api` in the current scope
  --> src\main.rs:10:20
   |
10 |     let api = Api::new(token);
   |                    ^^^ function or associated item not found in `telegram_bot::api::Api``

I believe that there is a definition for the "new" method on Api lib, but I don't know why this error happened.

**Comment by Morgan-iv** [comment]
crate version on crates.io is outdated, use direct git dependency like this:
`telegram-bot = { git = 'https://github.com/telegram-rs/telegram-bot' }`

**Comment by mrhajbabaei** [comment]
> crate version on crates.io is outdated, use direct git dependency like this:
> `telegram-bot = { git = 'https://github.com/telegram-rs/telegram-bot' }`

Thank you, It works :)

**Comment by timvisee** [comment]
> crate version on crates.io is outdated, use direct git dependency like this:
> `telegram-bot = { git = 'https://github.com/telegram-rs/telegram-bot' }`

@telegram-bot @gugahoa Could a new version be published on `crates.io` for this?

**Comment by gugahoa** [comment]
@timvisee a new version has been released https://github.com/telegram-rs/telegram-bot/issues/187#issuecomment-602079731
