### ISSUE TITLE
Strategy/Best practices for webhook use case

### ISSUE THREAD

**Issue by Alexx-G** [telegram-rs/telegram-bot#201]
Webhook method of getting updates is quite friendly for a number of platforms that offer free tiers (e.g. Heroku/AWS Lambda etc). Since it allows to pay only for actual usage, instead of leaving the app to poll permanently for updates.

Is it possible to use this crate for webhookts? I didn't find anything in examples/docs.

**Comment by gugahoa** [comment]
It's not currently possible, but we would welcome any contribution that makes it possible :)

**Comment by gugahoa** [comment]
There's this open PR that's outdated, but it's a good starting point https://github.com/telegram-rs/telegram-bot/pull/90

**Comment by Alexx-G** [comment]
Thanks for reply @gugahoa !
I see. I'm just playing Rust and trying to implement a pet project. I've checked that PR, it seems that adopting webhooks isn't as big deal as I though. Thus might be a good opportunity for some practice.
