### ISSUE TITLE
Add support for socks5 proxy

### ISSUE THREAD

**Issue by alextokarew** [telegram-rs/telegram-bot#203]
It would be nice to specify socks5 proxy settings for accessing telegram API in application itself and not to rely on external tools such as proxychains etc.

**Comment by bemyak** [comment]
You can use http proxy something like this:
```rust
use hyper::Client;
use hyper_proxy::{Intercept, Proxy, ProxyConnector};
use hyper_rustls::HttpsConnector;
use telegram_bot::HyperConnector;

...
let proxy_url = env::var("http_proxy");
let proxy = Proxy::new(Intercept::All, proxy_url.parse().unwrap());
let connector = ProxyConnector::from_proxy(HttpsConnector::new(), proxy)?;
let connector = Box::new(HyperConnector::new(
                Client::builder().build(connector),
            ))
let api = Api::with_connector(token, connector);
...
```

You can also configure Tor to be an HTTP proxy by adding `HTTPTunnelPort 9080` in `/etc/tor/torrc`.

**Comment by Nanue1** [comment]
![image](https://user-images.githubusercontent.com/12669211/173992393-9ddb7b23-799b-4aad-b551-e9d823a53571.png)
mismatched types
expected struct `hyper::client::Client<_>`
   found struct `Client<ProxyConnector<HttpConnector>, _>

**Comment by Nanue1** [comment]
how to fix this error?
