### ISSUE TITLE
It's not possible to get chat by string (username, groupname or channelname)

### ISSUE THREAD

**Issue by kworr** [telegram-rs/telegram-bot#209]
Official API supports sending strings to getChat:

https://core.telegram.org/bots/api#getchat

But ToChatRef doesn't accept strings. This means I can't operate on any chat given only `@reference`.

**Comment by ciyool** [comment]
Very useful API, hope to support as soon as possible

**Comment by ciyool** [comment]
```
let chat:Chat=api.send( telegram_bot::GetChat::new(telegram_bot_raw::types::refs::ChatRef::ChannelUsername(name))).await?;
println!("{:?}", chat);
```

**Comment by ciyool** [comment]
runs correctly
```
let chat:Chat=api.send( telegram_bot::GetChat::new(telegram_bot::types::refs::ChatRef::ChannelUsername(name))).await?;
println!("{:?}", chat);
```

**Comment by ciyool** [comment]
runs correctly

···
let chat:Chat=api.send( telegram_bot::GetChat::new(telegram_bot::types::refs::ChatRef::ChannelUsername("@username"))).await?;
println!("{:?}", chat);
···

**Comment by kworr** [comment]
Hey thank you! Sorry for being noob...
