### ISSUE TITLE
Run handlers in background

### ISSUE THREAD

**Issue by dbrgn** [telegram-rs/telegram-bot#22]
Right now the listener is blocking, so if there's a command handler that takes long, it will block the entire bot. Also, a panic will take down the entire chatbot.

Could we maybe run all handler code in background threads, e.g. using a [thread pool](https://crates.io/crates/threadpool)? That would be similar to the way Iron handles requests, I think.

To keep things simple, you could also offer two version of the listen loop, `listener.listen` and `listener.listen_threaded`.

**Comment by knsd** [comment]
There is only async interface now.
