### ISSUE TITLE
Issue with self-signed cert in a Docker container

### ISSUE THREAD

**Issue by rkudryashov** [telegram-rs/telegram-bot#236]
The question is how to setup SSL stuff to avoid the following error:

```
test-bot | Error: Error(Hyper(hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "../ssl/statem/statem_clnt.c", line: 1915 }]))) }, X509
VerifyResult { code: 19, error: "self signed certificate in certificate chain" }))))
test-bot exited with code 1
```

I created a repro-project: https://github.com/rkudryashov/telegram-bot-docker

You can reproduce the error by running `docker-compose up` in the root.

I read that there are a few options how to eliminate the error:

1) somehow sign/verify self-signed cert
2) somehow disable that check
3) use let's encrypt
4) use `setWebhook` method (https://core.telegram.org/bots/self-signed)

Does anyone have the practical experience with this?

**Comment by tarpaha** [comment]
Have same issue, all works when running app directly, but throws error in container. As I know certificate required only when using WebHook, it is not required for long polling.

**Comment by rkudryashov** [comment]
I found the solution: I just use Nginx as a forward proxy. I caught aforementioned error in both cases, WebHook and long polling. Eventually, I use long polling with Nginx. For this you need:

- specify Nginx config, for example, like this (I don't know what `resolver` line exactly makes):
```
server {
    location / {
        resolver 8.8.8.8 valid=30s ipv6=off;
        proxy_pass https://api.telegram.org;
    }
}
```
- specify API URL param as `http://nginx` in a chosen Telegram bot framework. So all outgoing requests from a bot will be passed through nginx

This helps me to avoid tedious setup of SSL/TLS stuff.

**Comment by bemyak** [comment]
You're using OpenSSL, which is dynamically linked in  container `rust:1.50` and then used in `debian:buster-slim`. This is **not a problem** since image `rust:1.50` is also based on buster, but still it is quite dangerous. Consider using `rustls` instead. To do this, in `Cargo.toml` specify the dependency as
```
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot", default-features = false , features = ["rustls"] }
```

The error itself is caused by debian missing CA certificates. To install and update them, replace `RUN` line in your Dockerfile with:
```
RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates
```
