### ISSUE TITLE
sending messages is slow

### ISSUE THREAD

**Issue by Rukenshia** [telegram-rs/telegram-bot#39]
Apparently sending a message via the `Api::send_message` function is very slow, at least for me. It takes up to 550ms to send a single message for me, where as my bot written in Go takes only ~50ms. 
I measured it using the `time` crate, using the function `time::precise_time_ns`.

**Comment by knsd** [comment]
Just checked master branch. About 400ms for the very first request (handshake, I guess) and about 70ms for following requests, and I have about 70ms ping delay to the Telegram API server.
