### ISSUE TITLE
Bot Platform 2.0

### ISSUE THREAD

**Issue by LukasKalbertodt** [telegram-rs/telegram-bot#40]
Telegram just released this: https://telegram.org/blog/bots-2-0

Tracking issue for implementing those features...

**Comment by dns2utf8** [comment]
I like the inline keyboard and edit message function.

Did you already start to implement it in a branch?

**Comment by LukasKalbertodt** [comment]
@dns2utf8 Sorry, no. I'm pretty busy at the moment, I created this issue only to remind me later. But if you want, I'd be happy if you start implementing!

**Comment by dns2utf8** [comment]
I started a new branch: https://github.com/dns2utf8/telegram-bot/tree/api_2.0
