### ISSUE TITLE
pinned_message is not handled

### ISSUE THREAD

**Issue by noiob** [telegram-rs/telegram-bot#43]
A message containing pinned_message (which in itself is a message object) crashes the bot wit the elusive error `JsonDecode(ApplicationError("No field for inferring message type is set"))`.

I'm not sure how to fix this myself, as the message object makes it non-trivial.
[Also I'm running the supergroup-migration branch and would like it to be added to stable]

**Comment by dns2utf8** [comment]
Thank you for the report. We are looking into it

**Comment by knsd** [comment]
[Fixed](https://github.com/telegram-rs/telegram-bot/blob/b4a55b99be96abeaf3544be63bed7acca04751ad/raw/src/types/message.rs#L90-L92) in `rewrite` branch.
