### ISSUE TITLE
Use POST requests for API instead of GET requests

### ISSUE THREAD

**Issue by xiagu** [telegram-rs/telegram-bot#49]
Right now the library uses a GET request to send messages. It also doesn't bother to URL encode the message text, which means that you can easily send messages with parameters in the text to invoke API features.

For example, you can send text like this
`test&disable_notification=true`
or this
`random reply&reply_to_message_id=1337`
or this
`test force reply&reply_markup={"force_reply":true}`
or this
`test reply keyboard&reply_markup={"keyboard":[[{"text":"Bad"},{"text":"Worse"}],[{"text":"Awful"}]],"resize_keyboard":true}`
or even this
`test inline&reply_markup={"inline_keyboard":[[{"text":"🔥","callback_data":"fire"},{"text":"👍","callback_data":"+1"},{"text":"😂","callback_data":"haha"}],[{"text":"google","url":"https://google.com/"}]]}`

Anyway this is really bad. For instance, if you write a Telegram <-> IRC mirror bot, or anything else where other users have control over the text of the message sent.

Using a POST request will completely avoid all of this junk.

**Comment by LukasKalbertodt** [comment]
Oh snap! That is bad!

Sadly, I don't really have time to fix any of this. Also see #48 (blocker). I think I should add a big, fat note to the README to tell everyone to not use this library until I managed to clean all this mess...

**Comment by knsd** [comment]
[Fixed](https://github.com/telegram-rs/telegram-bot/blob/b4a55b99be96abeaf3544be63bed7acca04751ad/lib/src/api.rs#L104) in `rewrite` branch.
