### ISSUE TITLE
New library name

### ISSUE THREAD

**Issue by LukasKalbertodt** [telegram-rs/telegram-bot#54]
We might want to change the crate name from `telegram-bot` to something else. To word crate names are a bit ugly in my opinion. Therefore it would be nice to come up with a nice one-word name. Note that we are likely to split this library into at least two crates: the standard one and a `-raw` version to include more low level features. So consider all name suggestions here with a `-raw` postfix, too.

In order to make it easier for everyone to express their opinion, I will (and you should, too) create one comment for each name suggestion. That way everyone can use emojis.

Also, before suggesting names, please make sure that the name is still available on `crates.io`.

**Comment by LukasKalbertodt** [comment]
Keep the old name: `telegram-bot`

**Comment by LukasKalbertodt** [comment]
`telegrust`

Advantage: the words `rust` and `telegram` share a common letter: `r` in the middle.

**Comment by LukasKalbertodt** [comment]
### `telegrs`

Advantage: same as `telegrust`, but shorter. Disadvantage: not really pronounceable.

**Comment by bjorn3** [comment]
# `telegram-rs`

**Comment by mehcode** [comment]
Just wanted to jump in and say I'm currently working on an full API client library for Telegram. I don't intend to target bots. I don't think `telegram-bot` is a bad name at all.

https://github.com/mehcode/telegram-rs

**Comment by mehcode** [comment]
## `rubot`

See https://github.com/telegram-rs/telegram-bot/issues/55#issuecomment-289173779 for more information
