### ISSUE TITLE
Change organization's name?

### ISSUE THREAD

**Issue by LukasKalbertodt** [telegram-rs/telegram-bot#55]
We might still change the name of this organization. 

I, however, think that this name is actually pretty good. Keep in mind that this organization might host multiple things, not just this library. Maybe we even want to maintain our own bot to... I don't know... mimic the playbot from IRC. So the organization is about "Telegram" and "Rust". 

Please signal with emoji on this comment whether or not you agree with me :)

**Comment by mehcode** [comment]
Just wanted to jump on and talk on an idea I had (that would involve changing the org's name).

Wouldn't it be neat to have a simple toolkit for writing simple bots that could interact with any service?

Enter *Rubot*

It's made up of several layers:

 - Connectors (`rubot-telegram`, `rubot-irc`, etc.)
 - API
 - Extensions ( think of like pre-packaged "do this thing" , see all the hubot packages)
