### ISSUE TITLE
Upgrade to serde 1.0

### ISSUE THREAD

**Issue by knsd** [telegram-rs/telegram-bot#59]
[Changelog](https://github.com/serde-rs/serde/releases/tag/v1.0.0)

**Comment by sb89** [comment]
I was looking to help out to get some more experience with Rust and I was looking at maybe helping out with this. I assume this change would be done in the rewrite branch? Is this correct?

**Comment by knsd** [comment]
Yes, that's right, I will merge `rewrite` to `master` on saturday, but I don't think it will be a problem.

**Comment by knsd** [comment]
Fixed in #63.
