### ISSUE TITLE
Add synchronous interface

### ISSUE THREAD

**Issue by knsd** [telegram-rs/telegram-bot#61]
It can be easily implemented via async interface, just with `Result` instead of `TelegramFuture`.

**Comment by sb89** [comment]
What would be involved in getting this done? Would this be a new method on the Api, something like send_sync? Would an additional Connector trait also be required that returns a Result instead of a TelegramFuture?
If so, the a synchronous Connector implementation would also be required?

**Comment by knsd** [comment]
Maybe it can be implemented via custom API type — SyncApi or something with the same methods except for the return type. Something like:

```rust
impl SyncApi {
    pub fn send<Req: Request>(&self, request: Req) -> Result<<Req::Response as Response>::Type> {
        self.core.run(self.async_api.send(request))
    }
}
```

What do you think?

**Comment by sb89** [comment]
Ok, pretty straightforward. When I was trying to picture how this would hang together, I imagined that it would just use a standard hyper request (without futures), as it seemed strange to create and use an event loop for running one synchronous request at a time. 

But I can see that using using the asynchronous api call within the synchronous call would required less code and reduce code duplication.

So I'm not sure, it's your call.

**Comment by knsd** [comment]
Also this implementation provides one more benefit — request timeouts, I think it's hard to do it without async backend.

Another question is how to implement sync stream of updates.
