### ISSUE TITLE
tuple structure UserId and others probably should have public fields

### ISSUE THREAD

**Issue by greyblake** [telegram-rs/telegram-bot#77]
The use case:
- I want to send a message to a particular use at specified moment

How I do it:
```rust
    let mut core = Core::new().unwrap();
    let api = Api::configure(token).build(core.handle());

    let send_message = SendMessage::new(UserId(user_id), "Hello");
    let future = api.send(send_message);
    core.run(future).unwrap();
```

Error message I get:
```
  --> src/main.rs:84:15
   |
84 |     let uid = UserId(user_id);
   |               ^^^^^^ did you mean `UserId { /* fields */ }`?
```

Solution proposal:
- Make the `UserId` field public.
Currently it is:
```
pub struct UserId(Integer);
```

But it works fine with:
```rust
pub struct UserId(pub Integer);
```

Probably some other structs must be updated this way as well. What do you think?

**Comment by knsd** [comment]
Hi!

Let me think about it. I have one argument against — it will cause breaking change if we want to change internal representation.

Maybe it's better to provide `From<i64>`, `From<u64>` etc, implementations.

**Comment by greyblake** [comment]
Hi, thanks for the quick reply.
It make sense as well)

**Comment by kworr** [comment]
I'll just add one more usecase. What about reading `i64` from `UserId`? If I want to write down list of users somewhere to store some data about them what should I do? I can only get `Hash` or `Debug` from it, why can't I directly use Integer as a prmiary key in the database?

**Comment by berkus** [comment]
Hi,

need to get the user id but its private, pls provide a way to get integer user id _somehow_.

**Comment by knsd** [comment]
Hi, you can use `From<Integer> for UserId` implementation, e.g.
```rust
let user_id: UserId = From::from(10);
let integer_user_id: Integer = user_id.into();
assert_eq!(integer_user_id, 10);
```

**Comment by berkus** [comment]
Thx, let me try it out!

**Comment by greyblake** [comment]
I've just tested it in 0.6.1. From/Into works as expected :+1: :heart:
