### ISSUE TITLE
repliying without a quote

### ISSUE THREAD

**Issue by GildedHonour** [telegram-rs/telegram-bot#81]
this code

    if let MessageKind::Text {ref data, ..} = message.kind {
                // Print received text message to stdout.
                println!("<{}>: {}", first_name, data);

                // Answer message with "Hi".
                api.spawn(message.text_reply(
                    format!("Hi, {}! You just wrote '{}'", first_name, data)
                ));
            }

repies with a quote. How to reply without one?

**Comment by knsd** [comment]
Hi.

You can use `text` method:
```rust
api.spawn(message.chat.text("Foo"));  // Send message to the same chat
api.spawn(message.from.text("Foo"));  // Send message directly to a user
```
