### ISSUE TITLE
Sending messages to users at any time

### ISSUE THREAD

**Issue by misuzu** [telegram-rs/telegram-bot#82]
Is there a way to send messages to some user using stored user id in database? There is no such examples and i can't find a way to manually create Message struct.

**Comment by knsd** [comment]
Hi, musuzu! You can transform your stored user id into `UserId` type using `Into` and use it's `text` method to compose `SendMessage` object.

Here is the full example:
```rust
extern crate telegram_bot;
extern crate tokio_core;

use std::env;

use tokio_core::reactor::Core;
use telegram_bot::*;

fn main() {
    let token = env::var("TELEGRAM_BOT_TOKEN").unwrap();
    let stored_user_id: i64 = env::args().nth(1).unwrap().parse().unwrap();
    let user_id: UserId = stored_user_id.into();

    let mut core = Core::new().unwrap();
    let api = Api::configure(token).build(core.handle()).unwrap();

    let future = api.send(user_id.text("Hello"));

    core.run(future).map(|_| ()).unwrap_or_default()
}
```

BTW, there is a [public constructor](https://telegram-rs.github.io/telegram-bot/telegram_bot/types/requests/struct.SendMessage.html#method.new) for `SendMessage` type.
