### ISSUE TITLE
Can the bot send the live location?

### ISSUE THREAD

**Issue by vityafx** [telegram-rs/telegram-bot#83]
Can the bot send the live location? I wanna use the bot for tracking. Should I just send new location via `telegram_bot::types::requests::SendLocation` repeatedly for this or there is another way?

**Comment by knsd** [comment]
It can since 0.6.1, see [examples/live_location.rs](https://github.com/telegram-rs/telegram-bot/blob/master/lib/examples/live_location.rs).
