### ISSUE TITLE
Send files

### ISSUE THREAD

**Issue by binomial0** [telegram-rs/telegram-bot#84]
The bot can currently recieve files, but it would be great if it could also send them.

**Comment by shouya** [comment]
This feature requires a lot more to do. Uploading file needs to POST with multipart type. And multipart isn't even officially implemented in Hyper currently.

**Comment by Chase22** [comment]
There's another repository implementing multipart into hyper:
https://github.com/ferristseng/rust-hyper-multipart-rfc7578

Might be worth a look

**Comment by shouya** [comment]
@Chase22 Thanks, this looks awesome!

In case you don't know yet, I have already done this feature in #97, using a non-official multipart crate for hyper.

**Comment by Chase22** [comment]
I've just seen it. That's the last thing is need in this libary for me to be able to use it. Thank you

**Comment by knsd** [comment]
Merged, usage [example](https://github.com/telegram-rs/telegram-bot/blob/525ac50a4c7dd1f0baedd6f010e186466cb33490/lib/examples/send.rs).
