### ISSUE TITLE
AnswerCallbackQuery with no text

### ISSUE THREAD

**Issue by shouya** [telegram-rs/telegram-bot#86]
Hi folks,

Telegram Bot API document recommends bot clients to answer to CallbackQuery with an answerCallbackQuery request. Quoted below ([source](https://core.telegram.org/bots/api#callbackquery)):

> NOTE: After the user presses a callback button, Telegram clients will display a progress bar until you call answerCallbackQuery. It is, therefore, necessary to react by calling answerCallbackQuery even if no notification to the user is needed (e.g., without specifying any of the optional parameters).

However, the text and other stuff are optional. In this crate, there's a request struct `AnswerCallbackQuery`, where the text is required. I think the field should be optional because sometimes alerts can be spammy when users interact to inline keyboard, especially when they're pressing quite frequently.

I think this can be improve to match the official doc by making the text field a `Option<Cow<'t, str>>` type. What do you think?

If you think it's worth-doing, I can file a pull request later. Thanks :)

**Comment by knsd** [comment]
Hi, thanks for notice!

I missed that note somehow. I think you're right and we should make this field optional and may be add a special method to `CanAnswerCallbackQuery` for empty answer.
