### ISSUE TITLE
bot get crushed when multi users use it at the same time 

### ISSUE THREAD

**Issue by MrReviewer** [telegram-rs/telegram-bot#88]
hi , we trying to create a bot ... actually , we almost finish it but when we trying to use it with my friends at the same time bot get crushed and do every command -that we save them in data base- mixed up and do every thing wrong , but when we use it one by one it do pretty well . please help us .

**Comment by menasheh** [comment]
Is that a problem with your bot or the library? share code!

**Comment by knsd** [comment]
Telegram doesn't allow two simultaneous `getUpdates` calls.
