### ISSUE TITLE
Invalid type: map, expected a string on updates stream

### ISSUE THREAD

**Issue by fominok** [telegram-rs/telegram-bot#92]
Yesterday (April 6) suddenly my bot stopped working, getting this JSON error when parsing Telegram update obects. I've checked that `simple` example of the telegram-bot library is crashing now too.
There were no recent changes in Telgram Bot API, so this behaviour is strange.

The error of the future, passed to updates stream:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: Error(Raw(Json(ErrorImpl { code: Message("invalid type: map, expected a string"),
line: 2, column: 268 })), State { next_error: None, backtrace: None })'
```

**Comment by knsd** [comment]
Hi, Evgeny. Can you provide an invalid update? It can be obtained via `https://api.telegram.org/bot<token>/getUpdates` request.

Also I think you can skip errors like this, see [errors](https://github.com/telegram-rs/telegram-bot/blob/master/lib/examples/errors.rs) example.

**Comment by fominok** [comment]
Hi, Fedor. Unfortunately, the update is too long, moved to 268th character and got nothing interesting.
Actually bot is not dying, just `api.stream().for_each()` returns this error even with empty body. Calling manually `getUpdates` removed bad message from queue, thank you. I'll improve my logging to get the reason of it, because it happens sometimes, this one was hard though. If got something I will write to this issue.

**Comment by Emulator000** [comment]
I just pushed a fix for this issue: https://github.com/telegram-rs/telegram-bot/pull/94

The same happened to me sometimes!

**Comment by Emulator000** [comment]
@knsd could you merge this? I'm still experiencing issues and I would like to update the crate to a version with this fix :-) Thanks!

**Comment by knsd** [comment]
Done, but I'm not sure that it's the same issue, because of error message `invalid type: map, expected a string`.

**Comment by upsuper** [comment]
I hit the same issue, but it seems master of the git repo doesn't have this issue anymore. Could you publish a new version with the fix?

**Comment by Emulator000** [comment]
@upsuper the project seems stalled, you can use my fork of this library if you want the last added fixes and features directly by pulling it from crates.io, the name is `telegram-bot-fork`

**Comment by gugahoa** [comment]
This issue seems to be closed, a new version of this crate will be released soon
