### ISSUE TITLE
Futures v0.2 [edit: Move to std futures]

### ISSUE THREAD

**Issue by Nukesor** [telegram-rs/telegram-bot#98]
Hi there :)

Futures just got updated to v0.2 about a week ago. As a result the examples break, if you try to run it with the newest version.

**Comment by berkus** [comment]
Hi, I believe futures are NOT compatible between 0.1 and 0.2 versions, I'd recommend sticking to v0.1 until async/await from https://github.com/rust-lang/rust/issues/50547 has landed in rustc.

**Comment by balthild** [comment]
Can I use async/await with this library currently? There's a library called [futures-await](https://github.com/alexcrichton/futures-await) that supports futures v0.1, but I can't work out it.

**Comment by gugahoa** [comment]
With futures stabilization near, it would be interesting to move to std futures
