### ISSUE TITLE
How to get bot commands from a message?

### ISSUE THREAD

**Issue by giovanniberti** [telegram-rs/telegram-bot#99]
I'm trying to get bot commands from a received message.
I see there is `MessageKind::Text::entities` which is a `Vec<MessageEntity>` (in the docs it says that a `MessageEntity` can be "hashtags, usernames, URLs, etc") but I can't find a method to get bot commands from`MessageEntity`. 
Looking trough the source I found that `MessageEntity` has all the fields I'd need (and a `kind` enum which has a `BotCommand` variant), but they're private. Do  I have to manually parse the message?

**Comment by Ealhad** [comment]
You do!

For example, here is what I did for one of my bots. ([source](https://cuisine.picdeballmer.science/Ealhad/NotificaRobot/src/master))

```rust
#[derive(Debug)]
enum Command {
    Ping,
    Unping,
    Pingall,
}

fn get_command(message: &str, bot_name: &str) -> Option<Command> {
    use Command::*;

    if !message.starts_with("/") {
        return None;
    }

    let mut cmd = message.clone();

    if cmd.ends_with(bot_name) {
        cmd = cmd.rsplitn(2, '@').skip(1).next().unwrap();
    }

    match cmd {
        "/ping" => Some(Ping),
        "/pingall" => Some(Pingall),
        "/unping" => Some(Unping),
        _ => None,
    }
}

```
In the update handler, I match the result of `get_command` to dispatch the data.

**Comment by kriomant** [comment]
I'm also interested in making `MessageEntity`'s fields public, is there any reason not to do it?

**Comment by gugahoa** [comment]
Currently they're public, does this solve this issue?
